### ISSUE TITLE
Release Script should set the Helm Chart Version

### ISSUE THREAD

**Issue by fhennig** [stackabletech/stackable-utils#13]
Once the version is set, the script should also set the non-nightly version in the Helm chart. It should then also generate the manifests from that (if it is left to the github action, it will make a new commit and it will not be set for the tag that the release script creates. So after the Helm chart version is set, run `make generate-manifests`)

**Comment by razvan** [comment]
This is now implemented a long time ago. The[ create-release-tag.sh](https://github.com/stackabletech/stackable-utils/blob/c5fcae27dd01ff69951648cbf8deba8aedcfb78a/release/create-release-tag.sh#L39) updates the version in `Cargo.toml` and then [regenerates](https://github.com/stackabletech/stackable-utils/blob/c5fcae27dd01ff69951648cbf8deba8aedcfb78a/release/create-release-tag.sh#L41C1-L41C1) the chart with the new version.
