### ISSUE TITLE
The release tool doesn't support workspaces with wildcards to define the members

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/stackable-utils#6]
I have not tested this, but according to @razvan the release tool currently does not support workspace crates which do not explicitly list their members but instead rely on wildcards.

```
# Works
members = ["rust/crd", "rust/operator", "rust/operator-lib"]
 
# Doesn't work
members = ["rust/*"]
```

**Comment by razvan** [comment]
Switched to `cargo-edit`
